version: '3.8'

services:
openemr:
image: openemr/openemr:latest
container_name: openemr_app
ports:
- "8080:80"
environment:
- OE_USER=admin
- OE_PASS=Admin123
- OE_DB_HOST=db
- OE_DB_USER=openemr
- OE_DB_PASS=openemrpass
- OE_DB_NAME=openemr
depends_on:
- db
volumes:
- openemr_data:/var/www/html

db:
image: mysql:5.7
container_name: openemr_db
restart: always
environment:
- MYSQL_ROOT_PASSWORD=rootpass
- MYSQL_DATABASE=openemr
- MYSQL_USER=openemr
- MYSQL_PASSWORD=openemrpass
volumes:
- db_data:/var/lib/mysql

volumes:
openemr_data:
db_data:
